---
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-debian:bookworm
  amd64: ghcr.io/home-assistant/amd64-base-debian:bookworm
  armv7: ghcr.io/home-assistant/armv7-base-debian:bookworm
labels:
  io.hass.name: "flask-rest-api"
  io.hass.description: "Flask REST-API functionality"
  org.opencontainers.image.title: "flask-rest-api"
  org.opencontainers.image.description: "Flask REST-API functionality"
  org.opencontainers.image.vendor: "Home Assistant Custom Add-on"
  org.opencontainers.image.source: "https://github.com/demey/hassio-addons/tree/master/flask-rest-api"
  org.opencontainers.image.licenses: "MIT"
