---
build_from:
  aarch64: "ghcr.io/hassio-addons/base:16.3.4"
  amd64: "ghcr.io/hassio-addons/base:16.3.4"
  armv7: "ghcr.io/hassio-addons/base:16.3.4"
  i386: "ghcr.io/hassio-addons/base:16.3.4"
labels:
  io.hass.name: "pdsync"
  io.hass.description: "Sync folders with Proton Drive"
  org.opencontainers.image.title: "pdsync"
  org.opencontainers.image.description: "Sync folders with Proton Drive"
  org.opencontainers.image.vendor: "Home Assistant Custom Add-on"
  org.opencontainers.image.source: "https://github.com/demey/hassio-addons/tree/master/proton-drive-sync"
  org.opencontainers.image.licenses: "MIT"
