---
version: "2025.05.20-10"
name: Proton Drive Folder Sync
slug: pdsync
description: Sync folders with Proton Drive
url: https://github.com/demey/hassio-addons/tree/master/proton-drive-sync
arch:
  - armv7
  - aarch64
  - amd64
  - i386
hassio_api: true
homeassistant_api: true
map:
  - share:rw
  - media:rw
options:
  folders: []
  days_keep: 3
  rclone_config: /share/pdsync/rclone.conf
  sync_interval: 600
schema:
  folders:
    - local_folder: str
      remote_folder: str
  days_keep: int(2,365)?
  rclone_config: str
  sync_interval: int(10,86400)?
startup: application
init: false
