---
version: "2025.07.16"
name: UA Alerts Monitor
slug: alertsmonitor
description: UA Alerts Monitor
url: https://github.com/demey/hassio-addons/tree/master/ua-alerts-monitor
arch:
  - armv7
  - aarch64
  - amd64
  - i386
hassio_api: true
homeassistant_api: true
map:
  - share:rw
options:
  max_message_length: 400
  channels: []
  skip_key_words: []
  delete_key_words: []
  critical_key_words: []
  sync_interval: 6
schema:
  max_message_length: int(100,600)?
  channels:
    - str
  skip_key_words: 
    - str
  delete_key_words: 
    - str
  critical_key_words: 
    - str
  sync_interval: int(6,120)?
startup: application
init: false
