---
version: "2.19.5"
name: Portainer
slug: portainer
description: Manage your Docker environment with ease
url: https://github.com/demey/hassio-addons/tree/master/portainer
advanced: true
ingress: true 
ingress_stream: true
panel_icon: mdi:docker
arch:
  - armv7
  - aarch64
  - amd64
init: false
hassio_api: true
docker_api: true
startup: services
init: false
options:
  log_level: debug
  agent_secret: ""
ports:
  8000/tcp: null
ports_description:
  8000/tcp: Edge Agent Api (Enable when managing remote edge agents)
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  agent_secret: password
